[package]
authors = ['ChainSafe Systems']
description = 'FRAME pallet to bond/unbond and transfer assets on other chains.'
edition = '2018'
license = 'LGPL-3.0-only'
name = 'pallet-remote-asset-manager'
readme = 'README.md'
repository = 'https://github.com/ChainSafe/PINT/'
version = '0.0.1'

[dependencies]
log = { version = "0.4.14", default-features = false }
serde = { version = "1.0.101", features = ["derive"], optional = true }
codec = { package = 'parity-scale-codec', version = '2.0.0', default-features = false, features = ['derive']}

# Substrate Dependencies
frame-support = { git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.5', default-features = false }
frame-system = { git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.5', default-features = false }
frame-benchmarking = { git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.5', default-features = false, optional = true }
pallet-staking = { git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.5', default-features = false }

# Polkadot Dependencies
xcm = { git = 'https://github.com/paritytech/polkadot', branch = 'release-v0.9.5', default-features = false }
xcm-executor = { git = 'https://github.com/paritytech/polkadot', branch = 'release-v0.9.5', default-features = false }

# Cumulus dependencies
cumulus-pallet-xcm = { git = 'https://github.com/paritytech/cumulus', branch = 'polkadot-v0.9.5', default-features = false }
cumulus-primitives-core = { git = 'https://github.com/paritytech/cumulus', branch = 'polkadot-v0.9.5', default-features = false }

# PINT dependencies
xcm-calls = {path = "../../primitives/xcm-calls", default-features = false }
primitives = { path = "../../primitives/primitives", default-features = false }
xcm-assets = { path = "../../primitives/xcm-assets", default-features = false }

orml-traits = { git = 'https://github.com/open-web3-stack/open-runtime-module-library', branch = 'master', default-features = false }

[dev-dependencies]
sp-core = { git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.5', default-features = false }
sp-io = { git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.5', default-features = false }
sp-runtime = { git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.5', default-features = false }

pallet-balances = { git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.5', default-features = false }

xcm-builder = { git = 'https://github.com/paritytech/polkadot', branch = 'release-v0.9.5', default-features = false }


[features]
default = ['std']
std = [
    'serde',
    'codec/std',
    'log/std',
    'frame-support/std',
    'frame-system/std',
    'pallet-staking/std',
    'xcm/std',

    'xcm-calls/std',
    'primitives/std',
    'xcm-assets/std',

    'xcm-executor/std',
    'cumulus-pallet-xcm/std',
    'cumulus-primitives-core/std',

    'orml-traits/std'
]
# this feature is only for compilation now
runtime-benchmarks = [
    'frame-benchmarking',
    'frame-support/runtime-benchmarks'
]

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']