[package]
authors = ['ChainSafe Systems']
description = 'FRAME pallet to bond/unbond and transfer assets on other chains.'
edition = '2018'
license = 'LGPL-3.0-only'
name = 'pallet-remote-asset-manager'
readme = 'README.md'
repository = 'https://github.com/ChainSafe/PINT/'
version = '0.0.1'

[features]
default = ['std']
std = [
    'serde',
    'codec/std',
    'frame-support/std',
    'frame-system/std',
    'xcm/std',
    'log/std',
    'xcm-calls/std',
    'xcm-executor/std',
    'cumulus-pallet-xcm/std',
    'cumulus-primitives-core/std',
]
# this feature is only for compilation now
runtime-benchmarks = [
    'frame-benchmarking',
    'frame-support/runtime-benchmarks'
]

[dependencies]
log = { version = "0.4.14", default-features = false }
serde = { version = "1.0.101", features = ["derive"], optional = true }

[dependencies.codec]
default-features = false
features = ['derive']
package = 'parity-scale-codec'
version = '2.0.0'

[dependencies.frame-support]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
branch = 'master'
version = '3.0.0'

[dependencies.frame-system]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
branch = 'master'
version = '3.0.0'

[dependencies.frame-benchmarking]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
branch = 'master'
version = '3.0.0'
optional = true

[dependencies.xcm]
default-features = false
git = 'https://github.com/paritytech/polkadot'
branch = 'master'

[dependencies.xcm-executor]
default-features = false
git = 'https://github.com/paritytech/polkadot'
branch = 'master'

[dependencies.cumulus-pallet-xcm]
default-features = false
git = 'https://github.com/paritytech/cumulus'
branch = 'master'

[dependencies.cumulus-primitives-core]
default-features = false
git = 'https://github.com/paritytech/cumulus'
branch = 'master'

[dependencies.xcm-calls]
default-features = false
path = '../../primitives/xcm-calls'
version = '0.0.1'

[dev-dependencies.pallet-staking]
git = 'https://github.com/paritytech/substrate.git'
branch = 'master'
version = '3.0.0'

[dev-dependencies.pallet-proxy]
git = 'https://github.com/paritytech/substrate.git'
branch = 'master'
version = '3.0.0'

[dev-dependencies.xcm-builder]
default-features = false
git = 'https://github.com/paritytech/polkadot'
branch = 'master'

[dev-dependencies.pallet-balances]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
branch = 'master'
version = '3.0.0'

[dev-dependencies.sp-core]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
branch = 'master'
version = '3.0.0'

[dev-dependencies.sp-io]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
branch = 'master'
version = '3.0.0'

[dev-dependencies.sp-runtime]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
branch = 'master'
version = '3.0.0'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']