[profile.release]
panic = 'unwind'

[workspace]
members = [
    'node',
    'pallets/*',
    'runtime',
]

# For local Apple M1 chip machine temporarily
# [patch.crates-io]
# rocksdb = { git = "https://github.com/hdevalence/rust-rocksdb.git" }
