reorder_imports = true
imports_granularity = "Crate"
hard_tabs = true
max_width = 120
use_small_heuristics = "Max"
comment_width = 100
wrap_comments = true
binop_separator = "Back"
trailing_comma = "Vertical"
use_field_init_shorthand = true
license_template_path = "HEADER-LICENSE"