version: 2.1

executors:
  test-executor:
    machine:
      image: ubuntu-2004:202010-01
    resource_class: xlarge

commands:
  rust_setup:
    description: Setup Rust Toolchain
    steps:
      - run:
          name: Setup Rust Toolchain
          command: |
            curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
            rustup default nightly-2021-04-18
            rustup component add clippy rustfmt
            rustup target add wasm32-unknown-unknown
            cargo install cargo-audit
  install_deps:
    steps:
      - run:
          name: Substrate Build Dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y git clang curl libssl-dev
  save_cargo_package_cache:
    description: Save cargo package cache for subsequent jobs
    steps:
      - save_cache:
          key: cargo-package-cache-{{ checksum "Cargo.lock" }}
          # paths are relative to /home/circleci/project/
          paths:
            - ../.cargo/git
            - ../.cargo/registry
            - ../.cargo/.package-cache
  restore_cargo_package_cache:
    description: Restore Cargo package cache from prev job
    steps:
      - run:
          name: Print dir
          command: |
            ls -all /usr/local/include
      - restore_cache:
          key: cargo-package-cache-{{ checksum "Cargo.lock" }}
      - run:
          name: Check cargo package cache
          command: |
            ls -all $HOME/.cargo
            du -ssh $HOME/.cargo
  build_setup:
    description: Sets up environment for future jobs
    steps:
      - checkout
      - rust_setup
      - install_deps

jobs:
  prefetch-crates:
    executor: test-executor
    description: Prefetch cargo crates for subsequent jobs.
    steps:
      - build_setup
      - restore_cargo_package_cache
      - run:
          name: Fetch workspace dependencies over network
          command: cargo fetch
      - save_cargo_package_cache
  format:
    executor: test-executor
    description: format check
    steps:
      - build_setup
      - run:
          name: Format check
          command: cargo fmt -- --check
  lint:
    executor: test-executor
    description: Lint Code
    steps:
      - build_setup
      - restore_cargo_package_cache
      - run:
          name: clippy check
          command: cargo clippy --all-targets
  test:
    executor: test-executor
    description: Run tests
    steps:
      - build_setup
      - restore_cargo_package_cache
      - run:
          name: Run Tests
          command: cargo test --all
  security:
    executor: test-executor
    description: Cargo audit
    steps:
      - build_setup
      - restore_cargo_package_cache
      - run:
          name: Check for known security issues in dependencies
          # TODO remove ignore when https://github.com/filecoin-project/rust-fil-proofs/issues/1403 resolved
          command: cargo audit --ignore RUSTSEC-2021-0011

workflows:
  test-code:
    jobs:
      - prefetch-crates
      - format
      - lint:
          requires:
            - prefetch-crates
      - test:
          requires:
            - prefetch-crates
  security:
    jobs:
      - prefetch-crates
      - security:
          requires:
            - prefetch-crates
