version: 2.1

executors:
  test-executor:
    resource_class: xlarge
    machine:
      image: ubuntu-2004:202010-01
      docker_layer_caching: true
    environment:
      IMAGE_NAME: chainsafe/pint
      CARGO_AUDIT: /home/circleci/.cargo/bin/cargo-audit
      RUSTC_WRAPPER: /home/circleci/.cargo/bin/sccache
      RUSTC_TOOLCHAIN: nightly-2021-04-18
      SCCACHE_CACHE_SIZE: 5G

commands:
  install_deps:
    steps:
      - run:
          name: Download Substrate Dependencies
          command: sudo apt-get update && sudo apt-get install -y git clang curl libssl-dev
  cargo_audit_setup:
    description: Install cargo-audit
    steps:
      - restore_cache:
          key: cargo-audit-{{ arch }}
      - run:
          name: Sets up cargo-audit
          command: |
            [[ ! -f ${CARGO_AUDIT} ]] && RUSTC_WRAPPER='' cargo install cargo-audit
            cargo audit --version
      - save_cache:
          key: cargo-audit-{{ arch }}
          paths:
            - ../.cargo/bin/cargo-audit
  sccache_setup:
    steps:
      - restore_cache:
          key: sccache-{{ arch }}
      - run: 
          name: Sets up Sccache
          command: |
            [[ ! -f ${RUSTC_WRAPPER} ]] \
            && curl -L https://github.com/mozilla/sccache/releases/download/\
            v0.2.15/sccache-v0.2.15-x86_64-unknown-linux-musl.tar.gz \
            | tar -zxvf - sccache-v0.2.15-x86_64-unknown-linux-musl/sccache \
            && sudo mv sccache-v0.2.15-x86_64-unknown-linux-musl/sccache ${RUSTC_WRAPPER} \
            && sudo chmod +x ${RUSTC_WRAPPER}
            sccache -s
      - save_cache:
          key: sccache-{{ arch }}
          paths:
            - ../.cargo/bin/sccache
  rust_setup:
    description: Sets up Rust Toolchain
    steps:
      - run:
          name: Sets up Rust Toolchain
          command: |
            curl https://sh.rustup.rs -sSf | sh -s -- -y \
            --default-toolchain "$RUSTC_TOOLCHAIN" \
            -c clippy rustfmt \
            -t wasm32-unknown-unknown \
            --profile minimal
      - restore_cache:
          key: cargo-package-cache-{{ checksum "Cargo.lock" }}-{{ arch }}
      - sccache_setup
  build_setup:
    description: Sets up environment for future jobs
    steps:
      - checkout
      - rust_setup
      - install_deps
  save_build_cache:
    description: Save cargo package cache for subsequent jobs
    steps:
      - save_cache:
          key: cargo-package-cache-{{ checksum "Cargo.lock" }}-{{ arch }}
          paths:
            - ../.cache/sccache
            - ../.cargo/git
            - ../.cargo/registry
            - ../.cargo/.package-cache
  login_dockerhub:
    description: Login DockerHub
    steps:
      - run: 
          name: Login DockerHub
          command: echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
  
jobs:
  format:
    executor: test-executor
    description: Format Check
    steps:
      - checkout
      - rust_setup
      - run:
          name: Format check
          command: cargo fmt -- --check
  lint:
    executor: test-executor
    description: Lint Code
    steps:
      - build_setup
      - run:
          name: Clippy Check
          command: cargo clippy --all-features
      - save_build_cache
  test:
    executor: test-executor
    description: Run tests
    steps:
      - build_setup
      - run:
          name: Run Tests
          command: cargo test --all-features
      - save_build_cache
  security:
    executor: test-executor
    description: Cargo audit
    steps:
      - checkout  
      - rust_setup
      - cargo_audit_setup
      - run:
          name: Check for known security issues in dependencies
          command: cargo audit
  docker-build-release:
    executor: test-executor
    description: Build Docker Image
    steps:
      - checkout
      - run:
          name: Build docker image
          command: BUILDKIT_PROGRESS=plain DOCKER_BUILDKIT=1 docker build -f docker/release.Dockerfile -t $IMAGE_NAME:latest .
      - run:
          name: Archive Docker image
          command: docker save -o image.tar $IMAGE_NAME
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar
  docker-run-e2e:
    executor: test-executor
    description: Build and run e2e tests
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Load Archived Docker Image
          command: docker load -i /tmp/workspace/image.tar
      - checkout
      - run:
          name: Build PINT launch Image
          command: |
            git submodule update --init
            docker build -f docker/launch.Dockerfile -t launch .
      - run:
          name: Run e2e tests
          command: |
            sudo curl -sL https://deb.nodesource.com/setup_16.x | sudo bash - \
            && sudo apt-get -qqy --no-install-recommends install nodejs -y \
            && cd js/e2e \
              && npm install \
              && npm run build \
              && npm run run
  docker-publish-latest:
    executor: test-executor
    description: Publish latest Docker Image
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Load Archived Docker Image
          command: docker load -i /tmp/workspace/image.tar
      - login_dockerhub
      - run:
          name: Publish Latest Docker Image
          command: docker push $IMAGE_NAME:latest
  docker-publish-tag:
    executor: test-executor
    description: Publish Tagged Docker Image
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Load Archived Docker Image
          command: docker load -i /tmp/workspace/image.tar
      - login_dockerhub
      - run:
          name: Publish Tagged Docker Image
          command: |
            IMAGE_TAG=${CIRCLE_TAG/v/''}
            docker tag $IMAGE_NAME:latest $IMAGE_NAME:$IMAGE_TAG
            docker push $IMAGE_NAME:latest
            docker push $IMAGE_NAME:$IMAGE_TAG

workflows:
  test-code:
    jobs:
      - format
      - lint
      - test
  security:
    jobs:
      - security
  docker:
    jobs:
      - docker-build-release
      - docker-run-e2e:
          requires:
            - docker-build-release
      - docker-publish-latest:
          requires:
            - docker-build-release
          filters:
            branches:
              only: main
      - docker-publish-tag:
          requires:
            - docker-publish-latest
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
