[package]
authors = ['ChainSafe Systems']
description = 'FRAME pallet to implement PINT SAFT registry.'
edition = '2018'
license = 'LGPL-3.0-only'
name = 'pallet-saft-registry'
readme = 'README.md'
repository = 'https://github.com/ChainSafe/PINT/'
version = '0.0.1'

[dependencies]
codec = { package = 'parity-scale-codec', version = '2.0.0', default-features = false, features = ['derive']}

# Substrate Dependencies
frame-support = { git = 'https://github.com/paritytech/substrate', default-features = false, branch = 'master' }
frame-system = { git = 'https://github.com/paritytech/substrate', branch = 'master', default-features = false }
frame-benchmarking = { git = 'https://github.com/paritytech/substrate', branch = 'master', default-features = false, optional = true }

# PINT dependencies
pallet-asset-index = {path = "../asset-index", default-features = false }


[dev-dependencies]
serde = { version = "1.0.101" }

sp-core = { git = 'https://github.com/paritytech/substrate', branch = 'master', default-features = false }
sp-io = { git = 'https://github.com/paritytech/substrate', branch = 'master', default-features = false }
sp-runtime = { git = 'https://github.com/paritytech/substrate', branch = 'master', default-features = false }

pallet-balances = { git = 'https://github.com/paritytech/substrate', branch = 'master', default-features = false }

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[features]
default = ['std']
std = [
    'codec/std',
    'frame-support/std',
    'frame-system/std',
    'pallet-asset-index/std'
]
runtime-benchmarks = [
    'frame-benchmarking',
    'frame-support/runtime-benchmarks',
    'pallet-asset-index/runtime-benchmarks',
]
