[package]
authors = ['ChainSafe Systems']
description = 'FRAME pallet to implement PINT asset index.'
edition = '2018'
license = 'LGPL-3.0-only'
name = 'pallet-asset-index'
readme = 'README.md'
repository = 'https://github.com/ChainSafe/PINT/'
version = '0.0.1'

[features]
default = ['std']
std = [
    'sp-std/std',
    'codec/std',
    'frame-support/std',
    'frame-system/std',
    'pallet-remote-asset-manager/std',
    'pallet-asset-depository/std',
    'pallet-price-feed/std',
    'xcm/std',
    'xcm-executor/std',
]
runtime-benchmarks = [
    'frame-benchmarking',
    'frame-support/runtime-benchmarks',
    'pallet-remote-asset-manager/runtime-benchmarks',
    'pallet-asset-depository/runtime-benchmarks',
    'pallet-price-feed/runtime-benchmarks',
    'pallet-chainlink-feed/runtime-benchmarks',
]

[dependencies.codec]
default-features = false
features = ['derive']
package = 'parity-scale-codec'
version = '2.0.0'

[dependencies.sp-std]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
branch = 'master'
version = '3.0.0'

[dependencies.frame-support]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
branch = 'master'
version = '3.0.0'

[dependencies.frame-system]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
branch = 'master'
version = '3.0.0'

[dependencies.frame-benchmarking]
default-features = false
git = 'https://github.com/paritytech/substrate'
branch = 'master'
optional = true

[dependencies.pallet-chainlink-feed]
default_features = false
package = 'pallet-chainlink-feed'
git = "https://github.com/smartcontractkit/chainlink-polkadot"
branch = 'master'
optional = true

[dependencies.xcm]
git = "https://github.com/paritytech/polkadot"
branch = 'master'
default-features = false

[dependencies.xcm-executor]
default-features = false
git = 'https://github.com/paritytech/polkadot'
branch = 'master'

[dependencies.pallet-remote-asset-manager]
default-features = false
path = '../remote-asset-manager'
version = '0.0.1'

[dependencies.pallet-asset-depository]
default-features = false
path = '../asset-depository'
version = '0.0.1'

[dependencies.pallet-price-feed]
default-features = false
path = '../price-feed'
version = '0.0.1'

[dev-dependencies]
serde = { version = "1.0.101" }

[dev-dependencies.pallet-balances]
git = 'https://github.com/paritytech/substrate.git'
branch = 'master'
version = '3.0.0'

[dev-dependencies.sp-core]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
branch = 'master'
version = '3.0.0'

[dev-dependencies.sp-io]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
branch = 'master'
version = '3.0.0'

[dev-dependencies.sp-runtime]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
branch = 'master'
version = '3.0.0'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']
