[package]
authors = ['ChainSafe Systems']
description = 'FRAME pallet to implement PINT committee.'
edition = '2018'
license = 'LGPL-3.0-only'
name = 'pallet-committee'
readme = 'README.md'
repository = 'https://github.com/ChainSafe/PINT/'
version = '0.0.1'

[dependencies]
serde = { version = "1.0.101", optional = true }
codec = { package = 'parity-scale-codec', version = '2.0.0', default-features = false, features = ['derive']}

# Substrate Dependencies
frame-support = { git = 'https://github.com/paritytech/substrate', default-features = false, branch = 'master' }
frame-system = { git = 'https://github.com/paritytech/substrate', branch = 'master', default-features = false }
frame-benchmarking = { git = 'https://github.com/paritytech/substrate', branch = 'master', default-features = false, optional = true }
sp-runtime = { git = 'https://github.com/paritytech/substrate', branch = 'master', default-features = false, optional = true }


[dev-dependencies]
sp-core = { git = 'https://github.com/paritytech/substrate', branch = 'master', default-features = false }
sp-io = { git = 'https://github.com/paritytech/substrate', branch = 'master', default-features = false }
sp-runtime = { git = 'https://github.com/paritytech/substrate', branch = 'master', default-features = false }

pallet-balances = { git = 'https://github.com/paritytech/substrate', branch = 'master', default-features = false }


[features]
default = ['std']
std = [
    'codec/std',
    'serde',
    'frame-support/std',
    'frame-system/std',
    'sp-runtime/std',
]
runtime-benchmarks = [
    'frame-benchmarking',
    'frame-support/runtime-benchmarks',
    'frame-system/runtime-benchmarks',
    'sp-runtime/runtime-benchmarks',
]

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']
