[package]
authors = ['ChainSafe Systems']
description = 'FRAME pallet with XCM bindings to FRAME pallets.'
edition = '2018'
license = 'LGPL-3.0-only'
name = 'xcm-calls'
readme = 'README.md'
repository = 'https://github.com/ChainSafe/PINT/'
version = '0.0.1'

[dependencies]
serde = { version = "1.0.101", features = ["derive"], optional = true }
codec = { package = 'parity-scale-codec', version = '2.0.0', default-features = false, features = ['derive'] }
frame-support = { git = 'https://github.com/paritytech/substrate', default-features = false, branch = 'master' }
frame-system = { git = 'https://github.com/paritytech/substrate', branch = 'master', default-features = false }

[dev-dependencies]
sp-core = { git = 'https://github.com/paritytech/substrate', branch = 'master' }
sp-runtime = { git = 'https://github.com/paritytech/substrate', branch = 'master' }
sp-staking = { git = 'https://github.com/paritytech/substrate', branch = 'master' }
frame-election-provider-support = { git = 'https://github.com/paritytech/substrate', branch = 'master' }
max-encoded-len = { git = 'https://github.com/paritytech/substrate', branch = 'master' }

## Substrate Pallet Dependencies
pallet-staking = { git = 'https://github.com/paritytech/substrate', branch = 'master', default-features = false }
pallet-proxy = { git = 'https://github.com/paritytech/substrate', branch = 'master', default-features = false }
pallet-balances = { git = 'https://github.com/paritytech/substrate', branch = 'master', default-features = false }
pallet-staking-reward-curve = { git = 'https://github.com/paritytech/substrate', branch = 'master' }
pallet-timestamp = { git = 'https://github.com/paritytech/substrate', branch = 'master' }
pallet-session = { git = 'https://github.com/paritytech/substrate', branch = 'master' }

# Polkadot Dependencies
xcm = { git = 'https://github.com/paritytech/polkadot', branch = 'master' }

[features]
default = ['std']
std = [
    'serde',
    'codec/std',
    'frame-support/std',
    'frame-system/std',
]
# this feature is only for compilation now
runtime-benchmarks = []

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']