name: Docker

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-18.04
  steps:
    - name: Build Docker Image
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        push: false
