name: Test Code

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  # Test code
  test-code:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Cache cargo registry
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}

      - name: Install toolchain
        uses: actions-rs/toolchain@v1

      - name: Test Code
        run: cargo test --all


  # Lint code
  clippy_check:
      runs-on: ubuntu-20.04

      steps:
        - name: Checkout Code
          uses: actions/checkout@v1

        - name: Cache cargo registry
          uses: actions/cache@v2
          with:
            path: |
              ~/.cargo/registry
              ~/.cargo/git
              target
            key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          
        - name: Install toolchain
          uses: actions-rs/toolchain@v1

        - name: Clippy Check
          uses: actions-rs/clippy-check@v1
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            args: --all-targets


  # Check if the code format is correct
  format_check:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install toolchain
        uses: actions-rs/toolchain@v1

      - name: Format check
        run: cargo fmt -- --check
